-- Drop all tables in reverse dependency order
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS PlaylistTrack;
DROP TABLE IF EXISTS UserPlaylist;
DROP TABLE IF EXISTS ChartHistory;
DROP TABLE IF EXISTS AwardHistory;
DROP TABLE IF EXISTS ArtistGenre;
DROP TABLE IF EXISTS Genre;
DROP TABLE IF EXISTS Collaboration;
DROP TABLE IF EXISTS Track;
DROP TABLE IF EXISTS Album;
DROP TABLE IF EXISTS Artist;
DROP TABLE IF EXISTS User;
SET FOREIGN_KEY_CHECKS = 1;
